name: Build Latest Backend Docker Image

on:
  push:
    branches: [ final ]
  workflow_dispatch:
  
jobs:
  build-and-push:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code
    - name: Build the Docker image
      run: |
        cd SBOLCanvasBackend
        docker build . --tag synbiohub/sbolcanvas:backend
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image to Docker Hub
      run: |
        docker push synbiohub/sbolcanvas:backend


