name: Build and Test Backend

defaults:
  run:
    working-directory: ./SBOLCanvasBackend

on:
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
          - final

jobs:
  test:
    name: Run Maven tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - name: Run tests
      run: mvn test -B
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code
    - name: Build the Docker image
      run: docker build . --tag synbiohub/sbolcanvas:backend
